// Generated by dts-bundle v0.3.0

declare module 'cu-events' {
    import HandlesCharacter from '__cu-events/classes/HandlesCharacter';
    import HandlesEnemyTarget from '__cu-events/classes/HandlesEnemyTarget';
    import HandlesFriendlyTarget from '__cu-events/classes/HandlesFriendlyTarget';
    var _default: {
        handlesCharacter: HandlesCharacter;
        handlesEnemyTarget: HandlesEnemyTarget;
        handlesFriendlyTarget: HandlesFriendlyTarget;
        on: (topic: string, callback: (info: any) => void) => any;
        off: (listener: any) => void;
        addListener: (topic: string, callback: (info: any) => void) => void;
        removeListener: (listener: any) => void;
    };
    export default _default;
}

declare module '__cu-events/classes/HandlesCharacter' {
    export default class HandlesCharacter {
        name: string;
        action: any;
        constructor();
        start(): void;
    }
}

declare module '__cu-events/classes/HandlesEnemyTarget' {
    export default class HandlesEnemyTarget {
        name: string;
        action: any;
        constructor();
        start(): void;
    }
}

declare module '__cu-events/classes/HandlesFriendlyTarget' {
    export default class HandlesFriendlyTarget {
        name: string;
        action: any;
        constructor();
        start(): void;
    }
}

