// Generated by dts-bundle v0.3.0

declare module 'cu-events' {
    import HandlesAnnouncements from '__cu-events/classes/HandlesAnnouncements';
    import HandlesCharacter from '__cu-events/classes/HandlesCharacter';
    import HandlesEnemyTarget from '__cu-events/classes/HandlesEnemyTarget';
    import HandlesFriendlyTarget from '__cu-events/classes/HandlesFriendlyTarget';
    import HandlesControlGame from '__cu-events/classes/HandlesControlGame';
    import HandlesControlGameScore from '__cu-events/classes/HandlesControlGameScore';
    var _default: {
        handlesAnnouncements: HandlesAnnouncements;
        handlesCharacter: HandlesCharacter;
        handlesEnemyTarget: HandlesEnemyTarget;
        handlesFriendlyTarget: HandlesFriendlyTarget;
        handlesControlGame: HandlesControlGame;
        handlesControlGameScore: HandlesControlGameScore;
        on: (topic: string, callback: (info: any) => void) => any;
        off: (listener: any) => void;
        addListener: (topic: string, callback: (info: any) => void) => void;
        removeListener: (listener: any) => void;
    };
    export default _default;
}

declare module '__cu-events/classes/HandlesAnnouncements' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    export default class HandlesAnnouncements {
        name: string;
    }
}

declare module '__cu-events/classes/HandlesCharacter' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    export default class HandlesCharacter {
        name: string;
    }
}

declare module '__cu-events/classes/HandlesEnemyTarget' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    export default class HandlesEnemyTarget {
        name: string;
    }
}

declare module '__cu-events/classes/HandlesFriendlyTarget' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    export default class HandlesFriendlyTarget {
        name: string;
    }
}

declare module '__cu-events/classes/HandlesControlGame' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    export default class HandlesControlGame {
        name: string;
    }
}

declare module '__cu-events/classes/HandlesControlGameScore' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    export default class HandlesControlGameScore {
        name: string;
    }
}

